name: disk_read_delay
compiled_code: /examples/disk/disk_read_delay.bpf.o
metrics:
  counters:
    - name: disk_read_stats
      help: "Disk read metrics. Index: 0=latency, 1=count, 2=flush_latency, 3=flush_count"
      table: disk_read_stats
      labels:
        - name: op_index
          size: 4
          decoders:
            - name: uint32
