name: disk_write_delay
metrics:
  counters:
    - name: disk_write_stats
      help: "Disk write metrics. Index: 0=total_latency, 1=count, 2=flush_latency, 3=flush_count"
      labels:
        - name: op_index
          size: 4
          decoders:
            - name: uint32
