name: cpu_freq_stat
metrics:
  counters:
    - name: cpu_freq_map
      help: "CPU frequency statistics per core (cur_freq kHz, total_freq, count)"
      labels:
        - name: cpu_id
          size: 4
          decoders:
            - name: uint32
