name: cpu_usage
metrics:
  counters:
    - name: cpu_time
      help: "Cumulative on-CPU time per PID (ns)"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
    - name: cpu_busy
      help: "Per-CPU core busy time (ns)"
      labels:
        - name: cpu_id
          size: 4
          decoders:
            - name: uint32
