name: irq_stat
metrics:
  counters:
    - name: irq_stats
      help: "Total count of execve calls by process name"
      labels:
        - name: comm
          size: 16
          decoders:
            - name: string
