name: net_tcp_retransmit
metrics:
  counters:
    - name: retrans_stats
      help: "Global TCP retransmission counter"
      labels:
        - name: idx
          size: 4
          decoders:
            - name: uint32
    - name: retrans_comm_map
      help: "TCP retransmission count per process name"
      labels:
        - name: comm
          size: 16
          decoders:
            - name: string
    - name: retrans_map
      help: "TCP retransmission count per PID with comm"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
