name: tcp_connect
metrics:
  counters:
    - name: conn_exporter
      help: "Total number of TCP connections per process"
      labels:
        - name: comm
          size: 16
          decoders:
            - name: string
