name: file_open_stat
metrics:
  counters:
    - name: open_counter
      help: "Total number of openat() calls per PID"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
    - name: open_fail_counter
      help: "Total number of failed openat() calls per PID"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
    - name: open_comm_counter
      help: "Total number of openat() calls per process name"
      labels:
        - name: comm
          size: 16
          decoders:
            - name: string
