name: read_stat
metrics:
  counters:
    - name: file_read_counter
      help: "Total number of sys_enter_read events per PID"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
