name: write_stat
compiled_code: /examples/file/write_stat.bpf.o
metrics:
  counters:
    - name: file_write_counter
      help: "Total number of sys_enter_write events per PID"
      table: file_write_counter
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
