name: mmap_stat
metrics:
  counters:
    - name: memo_counter
      help: "Total number of sys_enter_mmap events per PID"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
