name: page_swap_stat
metrics:
  counters:
    - name: total_delay
      help: "Total reclaim delay in nanoseconds per PID"
      labels:
        - name: pid
          size: 4
          decoders:
            - name: uint32
