name: page_fault_stat
metrics:
  counters:
    - name: counter_exporter
      help: "Total number of page faults per process"
      labels:
        - name: comm
          size: 16
          decoders:
            - name: string
